# Generated by Django 6.0.5 on 2026-06-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectifs', models.CharField(choices=[('orientation', 'Orientation professionnelle'), ('competences', 'Développement de compétences'), ('carriere', 'Conseils carrière'), ('projet', 'Accompagnement projet'), ('autre', 'Autre')], max_length=50, verbose_name='Objectifs principaux')),
                ('niveau_etudes', models.CharField(choices=[('lycee', 'Lycée'), ('licence', 'Licence/Bachelor'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('professionnel', 'Professionnel')], max_length=20, verbose_name="Niveau d'études")),
                ('besoins', models.TextField(help_text='Décrivez ce que vous attendez de votre mentor...', max_length=1000, verbose_name='Besoins spécifiques')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Recherche un mentor')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('a_mentor_actuel', models.BooleanField(default=False)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorat_mentee', to='comptes.profil')),
            ],
            options={
                'verbose_name': 'Mentoré',
                'verbose_name_plural': 'Mentorés',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaines_expertise', models.CharField(choices=[('informatique', 'Informatique'), ('mathematiques', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('ingenierie', 'Ingénierie'), ('data_science', 'Data Science'), ('intelligence_artificielle', 'Intelligence Artificielle'), ('entrepreneuriat', 'Entrepreneuriat'), ('autre', 'Autre')], max_length=50, verbose_name="Domaine d'expertise")),
                ('niveau_experience', models.CharField(choices=[('debutant', 'Débutant (1-2 ans)'), ('intermediaire', 'Intermédiaire (3-5 ans)'), ('avance', 'Avancé (6-10 ans)'), ('expert', 'Expert (+10 ans)')], max_length=20, verbose_name="Niveau d'expérience")),
                ('disponibilite', models.CharField(choices=[('hebdomadaire', '1-2 heures par semaine'), ('bimensuel', '3-4 heures par semaine'), ('quotidien', 'Plus de 5 heures par semaine')], max_length=20, verbose_name='Disponibilité')),
                ('bio_mentorat', models.TextField(help_text='Décrivez votre parcours, vos motivations à devenir mentor...', max_length=1000, verbose_name='Biographie de mentor')),
                ('titre_professionnel', models.CharField(blank=True, help_text='Ex: Coach en Data Science, Ingénieur logiciel senior...', max_length=120, verbose_name='Titre professionnel')),
                ('categories', models.CharField(blank=True, help_text='Liste courte des sujets séparés par des virgules.', max_length=200, verbose_name='Catégories de mentorat')),
                ('langues', models.CharField(blank=True, help_text='Ex: Français, Anglais.', max_length=150, verbose_name='Langues parlées')),
                ('tarif_par_seance', models.PositiveIntegerField(default=0, help_text='0 = mentorat gratuit. Numeria prélevé 20% de commission.', verbose_name='Tarif par séance (FCFA)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif comme mentor')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('nombre_mentees_actuels', models.PositiveIntegerField(default=0)),
                ('nombre_mentees_total', models.PositiveIntegerField(default=0)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorat_mentor', to='comptes.profil')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('professional_title', models.CharField(max_length=120, verbose_name='Titre professionnel')),
                ('bio', models.TextField(max_length=1200, verbose_name='Biographie professionnelle')),
                ('expertise_categories', models.TextField(help_text='Séparez les thèmes par des virgules.', verbose_name='Expertise / catégories')),
                ('cv', models.FileField(help_text='PDF, JPG, PNG, DOCX. Taille max 5MB.', upload_to='mentor_applications/cvs/', verbose_name='CV')),
                ('certificate', models.FileField(help_text='Un document de certification est requis.', upload_to='mentor_applications/certificats/', verbose_name='Certificat')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Profil LinkedIn')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='Site portfolio')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Profil GitHub')),
                ('recommendation_letter', models.FileField(blank=True, help_text='Optionnel', null=True, upload_to='mentor_applications/recommendations/', verbose_name='Lettre de recommandation')),
                ('additional_documents', models.FileField(blank=True, help_text='Optionnel', null=True, upload_to='mentor_applications/documents/', verbose_name='Documents supplémentaires')),
                ('social_profiles', models.TextField(blank=True, help_text='Liens vers d’autres profils sociaux, séparés par des virgules.', verbose_name='Réseaux sociaux')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut de la candidature')),
                ('rejection_notes', models.TextField(blank=True, verbose_name='Notes de rejet')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_mentor', to='comptes.profil')),
            ],
            options={
                'verbose_name': 'Candidature Mentor',
                'verbose_name_plural': 'Candidatures Mentors',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='RelationMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('objectifs', models.TextField(blank=True, max_length=1000, verbose_name='Objectifs de la relation')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_actives', to='mentorat.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_actives', to='mentorat.mentor')),
            ],
            options={
                'verbose_name': 'Relation de mentorat',
                'verbose_name_plural': 'Relations de mentorat',
                'ordering': ['-date_debut'],
                'unique_together': {('mentor', 'mentee')},
            },
        ),
        migrations.CreateModel(
            name='SeanceMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la séance')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('date_heure', models.DateTimeField(verbose_name='Date et heure')),
                ('duree_minutes', models.PositiveIntegerField(default=60, verbose_name='Durée (minutes)')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('modalite', models.CharField(choices=[('presentiel', 'Présentiel'), ('visio', 'Visioconférence'), ('telephone', 'Téléphone'), ('email', 'Email')], default='visio', max_length=20, verbose_name='Modalité')),
                ('notes_mentor', models.TextField(blank=True, verbose_name='Notes du mentor')),
                ('notes_mentee', models.TextField(blank=True, verbose_name='Notes du mentoré')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='mentorat.relationmentorat')),
            ],
            options={
                'verbose_name': 'Séance de mentorat',
                'verbose_name_plural': 'Séances de mentorat',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='DemandeMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('terminee', 'Terminée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('message', models.TextField(help_text='Présentez-vous et expliquez pourquoi vous souhaitez ce mentor...', max_length=500, verbose_name='Message au mentor')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes admin')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='mentorat.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to='mentorat.mentor')),
            ],
            options={
                'verbose_name': 'Demande de mentorat',
                'verbose_name_plural': 'Demandes de mentorat',
                'ordering': ['-date_creation'],
                'unique_together': {('mentee', 'mentor')},
            },
        ),
        migrations.CreateModel(
            name='PaiementSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.PositiveIntegerField(verbose_name='Montant total (FCFA)')),
                ('commission_numeria', models.PositiveIntegerField(verbose_name='Commission Numeria (FCFA)')),
                ('montant_mentor', models.PositiveIntegerField(verbose_name='Part mentor (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('preuve_soumise', 'Preuve soumise'), ('confirme', 'Confirmé'), ('echec', 'Échec / Annulé')], default='en_attente', max_length=20)),
                ('reference_mobile_money', models.CharField(blank=True, help_text='Numéro de transaction TMoney / Flooz / autre', max_length=100, verbose_name='Référence mobile money')),
                ('preuve_paiement', models.ImageField(blank=True, null=True, upload_to='paiements_mentorat/', verbose_name="Capture d'écran du paiement")),
                ('est_suspect', models.BooleanField(default=False, help_text='En escrow pour vérification admin', verbose_name='Paiement flaggé comme suspect')),
                ('raisons_suspect', models.TextField(blank=True, help_text='Séparées par |', verbose_name='Raisons du flagging')),
                ('date_deblocage', models.DateTimeField(blank=True, help_text='Après cette date, si pas de contestation, débloquer', null=True, verbose_name='Date de déblocage (escrow)')),
                ('date_submission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission de preuve')),
                ('raison_echec', models.TextField(blank=True, verbose_name="Raison de l'échec/contestation")),
                ('signature_mentoré', models.CharField(blank=True, help_text='Empêche modification du montant', max_length=64, verbose_name='Signature HMAC du mentoré')),
                ('adresse_ip_mentoré', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP du mentoré (audit)')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent (audit)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement_seance', to='paiements.paiement')),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='mentorat.seancementorat')),
            ],
            options={
                'verbose_name': 'Paiement de séance',
                'verbose_name_plural': 'Paiements de séances',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut', 'date_creation'], name='mentorat_pa_statut_7ef6ef_idx'), models.Index(fields=['est_suspect'], name='mentorat_pa_est_sus_048c59_idx'), models.Index(fields=['reference_mobile_money'], name='mentorat_pa_referen_a0104a_idx')],
            },
        ),
    ]
