# Generated by Django 6.0.3 on 2026-04-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectifs', models.CharField(choices=[('orientation', 'Orientation professionnelle'), ('competences', 'Développement de compétences'), ('carriere', 'Conseils carrière'), ('projet', 'Accompagnement projet'), ('autre', 'Autre')], max_length=50, verbose_name='Objectifs principaux')),
                ('niveau_etudes', models.CharField(choices=[('lycee', 'Lycée'), ('licence', 'Licence/Bachelor'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('professionnel', 'Professionnel')], max_length=20, verbose_name="Niveau d'études")),
                ('besoins', models.TextField(help_text='Décrivez ce que vous attendez de votre mentor...', max_length=1000, verbose_name='Besoins spécifiques')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Recherche un mentor')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('a_mentor_actuel', models.BooleanField(default=False)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorat_mentee', to='comptes.profil')),
            ],
            options={
                'verbose_name': 'Mentoré',
                'verbose_name_plural': 'Mentorés',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaines_expertise', models.CharField(choices=[('informatique', 'Informatique'), ('mathematiques', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('ingenierie', 'Ingénierie'), ('data_science', 'Data Science'), ('intelligence_artificielle', 'Intelligence Artificielle'), ('entrepreneuriat', 'Entrepreneuriat'), ('autre', 'Autre')], max_length=50, verbose_name="Domaine d'expertise")),
                ('niveau_experience', models.CharField(choices=[('debutant', 'Débutant (1-2 ans)'), ('intermediaire', 'Intermédiaire (3-5 ans)'), ('avance', 'Avancé (6-10 ans)'), ('expert', 'Expert (+10 ans)')], max_length=20, verbose_name="Niveau d'expérience")),
                ('disponibilite', models.CharField(choices=[('hebdomadaire', '1-2 heures par semaine'), ('bimensuel', '3-4 heures par semaine'), ('quotidien', 'Plus de 5 heures par semaine')], max_length=20, verbose_name='Disponibilité')),
                ('bio_mentorat', models.TextField(help_text='Décrivez votre parcours, vos motivations à devenir mentor...', max_length=1000, verbose_name='Biographie de mentor')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif comme mentor')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('nombre_mentees_actuels', models.PositiveIntegerField(default=0)),
                ('nombre_mentees_total', models.PositiveIntegerField(default=0)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorat_mentor', to='comptes.profil')),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='RelationMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('objectifs', models.TextField(blank=True, max_length=1000, verbose_name='Objectifs de la relation')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_actives', to='mentorat.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_actives', to='mentorat.mentor')),
            ],
            options={
                'verbose_name': 'Relation de mentorat',
                'verbose_name_plural': 'Relations de mentorat',
                'ordering': ['-date_debut'],
                'unique_together': {('mentor', 'mentee')},
            },
        ),
        migrations.CreateModel(
            name='SeanceMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la séance')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('date_heure', models.DateTimeField(verbose_name='Date et heure')),
                ('duree_minutes', models.PositiveIntegerField(default=60, verbose_name='Durée (minutes)')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('modalite', models.CharField(choices=[('presentiel', 'Présentiel'), ('visio', 'Visioconférence'), ('telephone', 'Téléphone'), ('email', 'Email')], default='visio', max_length=20, verbose_name='Modalité')),
                ('notes_mentor', models.TextField(blank=True, verbose_name='Notes du mentor')),
                ('notes_mentee', models.TextField(blank=True, verbose_name='Notes du mentoré')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='mentorat.relationmentorat')),
            ],
            options={
                'verbose_name': 'Séance de mentorat',
                'verbose_name_plural': 'Séances de mentorat',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='DemandeMentorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('terminee', 'Terminée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('message', models.TextField(help_text='Présentez-vous et expliquez pourquoi vous souhaitez ce mentor...', max_length=500, verbose_name='Message au mentor')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='mentorat.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to='mentorat.mentor')),
            ],
            options={
                'verbose_name': 'Demande de mentorat',
                'verbose_name_plural': 'Demandes de mentorat',
                'ordering': ['-date_creation'],
                'unique_together': {('mentee', 'mentor')},
            },
        ),
    ]
