# Generated by Django 6.0.3 on 2026-04-13 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='tarif_par_seance',
            field=models.PositiveIntegerField(default=0, help_text='0 = mentorat gratuit. Numeria prélevé 20% de commission.', verbose_name='Tarif par séance (FCFA)'),
        ),
        migrations.CreateModel(
            name='PaiementSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.PositiveIntegerField(verbose_name='Montant total (FCFA)')),
                ('commission_numeria', models.PositiveIntegerField(verbose_name='Commission Numeria (FCFA)')),
                ('montant_mentor', models.PositiveIntegerField(verbose_name='Part mentor (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('preuve_soumise', 'Preuve soumise'), ('confirme', 'Confirmé'), ('echec', 'Échec / Annulé')], default='en_attente', max_length=20)),
                ('reference_mobile_money', models.CharField(blank=True, help_text='Numéro de transaction TMoney / Flooz / autre', max_length=100, verbose_name='Référence mobile money')),
                ('preuve_paiement', models.ImageField(blank=True, null=True, upload_to='paiements_mentorat/', verbose_name="Capture d'écran du paiement")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='mentorat.seancementorat')),
            ],
            options={
                'verbose_name': 'Paiement de séance',
                'verbose_name_plural': 'Paiements de séances',
                'ordering': ['-date_creation'],
            },
        ),
    ]
