# Generated by Django 6.0.3 on 2026-04-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0002_mentor_tarif_par_seance_paiementseance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementseance',
            name='adresse_ip_mentoré',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP du mentoré (audit)'),
        ),
        migrations.AddField(
            model_name='paiementseance',
            name='date_deblocage',
            field=models.DateTimeField(blank=True, help_text='Après cette date, si pas de contestation, débloquer', null=True, verbose_name='Date de déblocage (escrow)'),
        ),
        migrations.AddField(
            model_name='paiementseance',
            name='date_submission',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission de preuve'),
        ),
        migrations.AddField(
            model_name='paiementseance',
            name='est_suspect',
            field=models.BooleanField(default=False, help_text='En escrow pour vérification admin', verbose_name='Paiement flaggé comme suspect'),
        ),
        migrations.AddField(
            model_name='paiementseance',
            name='raison_echec',
            field=models.TextField(blank=True, verbose_name="Raison de l'échec/contestation"),
        ),
        migrations.AddField(
            model_name='paiementseance',
            name='raisons_suspect',
            field=models.TextField(blank=True, help_text='Séparées par |', verbose_name='Raisons du flagging'),
        ),
        migrations.AddField(
            model_name='paiementseance',
            name='signature_mentoré',
            field=models.CharField(blank=True, help_text='Empêche modification du montant', max_length=64, verbose_name='Signature HMAC du mentoré'),
        ),
        migrations.AddField(
            model_name='paiementseance',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='User-Agent (audit)'),
        ),
        migrations.AddIndex(
            model_name='paiementseance',
            index=models.Index(fields=['statut', 'date_creation'], name='mentorat_pa_statut_7ef6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementseance',
            index=models.Index(fields=['est_suspect'], name='mentorat_pa_est_sus_048c59_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementseance',
            index=models.Index(fields=['reference_mobile_money'], name='mentorat_pa_referen_a0104a_idx'),
        ),
    ]
