# Generated by Django 6.0.3 on 2026-05-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0003_paiementseance_adresse_ip_mentoré_and_more'),
        ('paiements', '0006_add_missing_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementseance',
            name='paiement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement_seance', to='paiements.paiement'),
        ),
    ]
