# Generated by Django 6.0.3 on 2026-05-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_profil_role'),
        ('mentorat', '0004_paiementseance_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='categories',
            field=models.CharField(blank=True, help_text='Liste courte des sujets séparés par des virgules.', max_length=200, verbose_name='Catégories de mentorat'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='langues',
            field=models.CharField(blank=True, help_text='Ex: Français, Anglais.', max_length=150, verbose_name='Langues parlées'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='titre_professionnel',
            field=models.CharField(blank=True, help_text='Ex: Coach en Data Science, Ingénieur logiciel senior...', max_length=120, verbose_name='Titre professionnel'),
        ),
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('professional_title', models.CharField(max_length=120, verbose_name='Titre professionnel')),
                ('bio', models.TextField(max_length=1200, verbose_name='Biographie professionnelle')),
                ('expertise_categories', models.TextField(help_text='Séparez les thèmes par des virgules.', verbose_name='Expertise / catégories')),
                ('cv', models.FileField(help_text='PDF, JPG, PNG, DOCX. Taille max 5MB.', upload_to='mentor_applications/cvs/', verbose_name='CV')),
                ('certificate', models.FileField(help_text='Un document de certification est requis.', upload_to='mentor_applications/certificats/', verbose_name='Certificat')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Profil LinkedIn')),
                ('portfolio', models.URLField(blank=True, null=True, verbose_name='Site portfolio')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Profil GitHub')),
                ('recommendation_letter', models.FileField(blank=True, help_text='Optionnel', null=True, upload_to='mentor_applications/recommendations/', verbose_name='Lettre de recommandation')),
                ('additional_documents', models.FileField(blank=True, help_text='Optionnel', null=True, upload_to='mentor_applications/documents/', verbose_name='Documents supplémentaires')),
                ('social_profiles', models.TextField(blank=True, help_text='Liens vers d’autres profils sociaux, séparés par des virgules.', verbose_name='Réseaux sociaux')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut de la candidature')),
                ('rejection_notes', models.TextField(blank=True, verbose_name='Notes de rejet')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_mentor', to='comptes.profil')),
            ],
            options={
                'verbose_name': 'Candidature Mentor',
                'verbose_name_plural': 'Candidatures Mentors',
                'ordering': ['-date_created'],
            },
        ),
    ]
