# Generated by Django 6.0.5 on 2026-05-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorat', '0005_mentor_categories_mentor_langues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandementorat',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Notes admin'),
        ),
    ]
