# Generated by Django 6.0.5 on 2026-06-01 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
        ('formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('mixx', 'Mixx by Yas (T-Money)'), ('moov', 'Moov Money (Flooz)'), ('card', 'Carte bancaire / VISA')], max_length=20, null=True)),
                ('provider', models.CharField(choices=[('sandbox', 'Sandbox (test)'), ('paygate', 'PayGate Global'), ('stripe', 'Stripe'), ('mixx', 'Mixx by YAS'), ('moov', 'Moov Money'), ('fedapay', 'FedaPay'), ('cinetpay', 'CinetPay')], default='sandbox', max_length=20)),
                ('devise', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar US (USD)'), ('GHS', 'Cedi ghaneen (GHS)')], default='XOF', max_length=10)),
                ('reference_numeria', models.CharField(max_length=200, unique=True)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('montant_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_plateforme', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('reference_provider', models.CharField(blank=True, max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='cours.course')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='formation.formation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField(verbose_name='Raison du remboursement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuve'), ('refuse', 'Refuse'), ('traite', 'Traite')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True, default='')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remboursement', to='paiements.paiement')),
            ],
            options={
                'verbose_name': 'Demande de remboursement',
                'verbose_name_plural': 'Demandes de remboursement',
                'ordering': ['-date_demande'],
            },
        ),
    ]
