# Generated by Django 6.0.3 on 2026-04-07 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar US (USD)'), ('GHS', 'Cedi ghanéen (GHS)')], default='XOF', max_length=3, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('provider', models.CharField(choices=[('sandbox', 'Sandbox (test)'), ('stripe', 'Stripe'), ('fedapay', 'FedaPay'), ('cinetpay', 'CinetPay'), ('mixx', 'Mixx by YAS'), ('payدunya', 'PayDunya')], default='sandbox', max_length=20, verbose_name='Provider de paiement')),
                ('reference_provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence provider')),
                ('reference_numeria', models.CharField(max_length=50, unique=True, verbose_name='Référence Numeria')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='cours.Course')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RemboursementDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.TextField(verbose_name='Raison du remboursement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('traite', 'Traité')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True, null=True)),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remboursement', to='paiements.paiement')),
            ],
            options={
                'verbose_name': 'Demande de remboursement',
                'verbose_name_plural': 'Demandes de remboursement',
                'ordering': ['-date_demande'],
            },
        ),
    ]
