# Generated by Django 6.0.3 on 2026-04-14 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_tag_cours_competences_visees_cours_cours_prerequises_and_more'),
        ('paiements', '0002_alter_paiement_cours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='montant',
        ),
        migrations.AddField(
            model_name='paiement',
            name='frais_plateforme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frais plateforme'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='ip_adresse',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant final (apres frais)'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant initial'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='devise',
            field=models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar US (USD)'), ('GHS', 'Cedi ghaneen (GHS)')], default='XOF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='provider',
            field=models.CharField(choices=[('sandbox', 'Sandbox (test)'), ('stripe', 'Stripe'), ('fedapay', 'FedaPay'), ('cinetpay', 'CinetPay'), ('mixx', 'Mixx by YAS'), ('paydunya', 'PayDunya')], default='sandbox', max_length=20, verbose_name='Provider de paiement'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_numeria',
            field=models.CharField(max_length=50, unique=True, verbose_name='Reference Numeria'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='reference_provider',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Reference provider'),
        ),
        migrations.AlterField(
            model_name='remboursementdemande',
            name='notes_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remboursementdemande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuve'), ('refuse', 'Refuse'), ('traite', 'Traite')], default='en_attente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['etudiant', '-date_creation'], name='paiements_p_etudian_40a416_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='paiements_p_statut_b61122_idx'),
        ),
    ]
