# Generated by Django 6.0.3 on 2026-04-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_remove_paiement_montant_paiement_frais_plateforme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursementdemande',
            name='notes_admin',
            field=models.TextField(blank=True, default=''),
        ),
    ]
