# Generated by Django 6.0.3 on 2026-04-15 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
        ('paiements', '0004_alter_remboursementdemande_notes_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='formation_inscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='formation.inscriptionformation'),
        ),
    ]
