# Generated by Django 6.0.3 on 2026-04-16 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_tag_cours_competences_visees_cours_cours_prerequises_and_more'),
        ('formation', '0001_initial'),
        ('paiements', '0005_paiement_formation_inscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['provider'], name='paiements_p_provide_51c3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['reference_provider'], name='paiements_p_referen_189e17_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['etudiant', 'statut', '-date_creation'], name='paiements_p_etudian_9d0245_idx'),
        ),
    ]
