# Generated by Django 6.0.3 on 2026-04-14 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0002_tag_cours_competences_visees_cours_cours_prerequises_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiquesGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('nombre_utilisateurs_actifs', models.IntegerField(default=0)),
                ('nombre_etudiants_inscrits', models.IntegerField(default=0)),
                ('nombre_cours_suivis', models.IntegerField(default=0)),
                ('nombre_certificats_gagnes', models.IntegerField(default=0)),
                ('nombre_paiements_jour', models.IntegerField(default=0)),
                ('revenus_jour', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_sessions_jour', models.IntegerField(default=0)),
                ('taux_engagement', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Taux d'engagement (%)")),
            ],
            options={
                'verbose_name': 'Statistique globale',
                'verbose_name_plural': 'Statistiques globales',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AnalytiquesCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_consultations', models.IntegerField(default=0)),
                ('nombre_inscriptions', models.IntegerField(default=0)),
                ('nombre_completions', models.IntegerField(default=0)),
                ('taux_completion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('temps_moyen_par_etudiant', models.IntegerField(default=0, help_text='En minutes')),
                ('nombre_questions_posees', models.IntegerField(default=0)),
                ('nombre_discussions', models.IntegerField(default=0)),
                ('revenus_totaux', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_transactions', models.IntegerField(default=0)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('cours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='cours.cours')),
            ],
            options={
                'verbose_name': 'Analytique cours',
                'verbose_name_plural': 'Analytiques cours',
            },
        ),
        migrations.CreateModel(
            name='AnalytiquesUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_connexions', models.IntegerField(default=0)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('premiere_connexion', models.DateTimeField(blank=True, null=True)),
                ('nombre_cours_suivis', models.IntegerField(default=0)),
                ('nombre_lecons_completees', models.IntegerField(default=0)),
                ('nombre_exercices_termines', models.IntegerField(default=0)),
                ('nombre_certificats', models.IntegerField(default=0)),
                ('temps_total_apprentissage', models.IntegerField(default=0, help_text='En minutes')),
                ('score_engagement', models.IntegerField(default=0, help_text='Score 0-100')),
                ('matieres_favorites', models.CharField(blank=True, max_length=200)),
                ('niveau_prefere', models.CharField(blank=True, max_length=50)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytique utilisateur',
                'verbose_name_plural': 'Analytiques utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='EveneementUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('connexion', 'Connexion'), ('lecture_cours', 'Lecture de cours'), ('completion_lecon', 'Complétion de leçon'), ('reponse_exercice', 'Réponse exercice'), ('achat_cours', 'Achat de cours'), ('telechargement_certificat', 'Téléchargement certificat'), ('publication_discussion', 'Publication discussion'), ('download_ressource', 'Téléchargement ressource'), ('interaction_forum', 'Interaction forum'), ('autre', 'Autre')], max_length=50, verbose_name="Type d'événement")),
                ('description', models.TextField(blank=True)),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='cours.cours')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement utilisateur',
                'verbose_name_plural': 'Événements utilisateurs',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', '-date_creation'], name='analytics_e_utilisa_50c423_idx'), models.Index(fields=['type_evenement'], name='analytics_e_type_ev_e22125_idx')],
            },
        ),
    ]
