# Generated by Django 6.0.5 on 2026-05-30 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_contactmessage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('replied_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='pages.contactmessage', verbose_name='Message de contact')),
                ('replied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Répondu par')),
            ],
            options={
                'verbose_name': 'Réponse contact',
                'verbose_name_plural': 'Réponses contact',
                'ordering': ['replied_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('contact_replied', 'Réponse contact'), ('candidacy_accepted', 'Candidature acceptée'), ('candidacy_rejected', 'Candidature rejetée'), ('candidacy_waitlisted', 'Candidature en attente'), ('candidacy_reviewing', 'Candidature en revue'), ('mentorship_accepted', 'Mentorat accepté'), ('mentorship_rejected', 'Mentorat rejeté'), ('user_activated', 'Utilisateur activé'), ('user_deactivated', 'Utilisateur désactivé'), ('notification_sent', 'Notification envoyée')], max_length=50, verbose_name="Type d'action")),
                ('description', models.TextField(verbose_name='Description')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_actions', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur concerné')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activités",
                'ordering': ['-performed_at'],
            },
        ),
    ]
