# Generated by Django 6.0.5 on 2026-05-30 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('cours', 'Cours'), ('article', 'Article'), ('lecon', 'Leçon')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('version_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version de contenu',
                'verbose_name_plural': 'Versions de contenu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/media/', verbose_name='Fichier')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('other', 'Autre')], default='image', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadé le')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Média uploadé',
                'verbose_name_plural': 'Médias uploadés',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
