# Generated by Django 6.0.5 on 2026-06-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='À propos de Numeria Institute', max_length=200, verbose_name='Titre')),
                ('content', models.TextField(default='Numeria Institute est...', verbose_name='Contenu')),
                ('mission_title', models.CharField(default='Notre mission', max_length=200, verbose_name='Titre mission')),
                ('mission_content', models.TextField(default='...', verbose_name='Contenu mission')),
                ('vision_title', models.CharField(default='Notre vision', max_length=200, verbose_name='Titre vision')),
                ('vision_content', models.TextField(default='...', verbose_name='Contenu vision')),
                ('team', models.JSONField(default=list, verbose_name='Équipe (JSON)')),
                ('meta_title', models.CharField(default='À propos - Numeria Institute', max_length=60, verbose_name='Meta title')),
                ('meta_description', models.TextField(default='...', max_length=160, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Page À propos',
                'verbose_name_plural': 'Page À propos',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=300, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('status', models.CharField(choices=[('unread', 'Non lu'), ('read', 'Lu'), ('replied', 'Répondu')], default='unread', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contactez-nous', max_length=200, verbose_name='Titre')),
                ('intro', models.TextField(default='Nous sommes là pour vous aider.', verbose_name='Introduction')),
                ('address', models.TextField(default='Lomé, Togo', verbose_name='Adresse')),
                ('phone', models.CharField(default='+228 XX XX XX XX', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(default='numeriainstitude@gmail.com', max_length=254, verbose_name='Email')),
                ('hours', models.TextField(default='Lundi-Vendredi: 9h-18h', verbose_name='Horaires')),
                ('meta_title', models.CharField(default='Contact - Numeria Institute', max_length=60, verbose_name='Meta title')),
                ('meta_description', models.TextField(default='...', max_length=160, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': 'Page Contact',
                'verbose_name_plural': 'Page Contact',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='Scientific Computing & AI', max_length=100, verbose_name='Badge héros')),
                ('hero_title', models.TextField(default='La science accessible à tous les esprits curieux', verbose_name='Titre héros')),
                ('hero_description', models.TextField(default='Des cours scientifiques de qualité...', verbose_name='Description héros')),
                ('hero_cta_primary_text', models.CharField(default='Découvrir les cours', max_length=50, verbose_name='Texte bouton principal')),
                ('hero_cta_primary_url', models.CharField(default="{% url 'cours:catalogue' %}", max_length=200, verbose_name='URL bouton principal')),
                ('hero_cta_secondary_text', models.CharField(default='Créer un compte', max_length=50, verbose_name='Texte bouton secondaire')),
                ('hero_cta_secondary_url', models.CharField(default="{% url 'comptes:inscription' %}", max_length=200, verbose_name='URL bouton secondaire')),
                ('stats_students', models.IntegerField(default=1500, verbose_name="Nombre d'étudiants")),
                ('stats_courses', models.IntegerField(default=25, verbose_name='Nombre de cours')),
                ('stats_countries', models.IntegerField(default=15, verbose_name='Nombre de pays')),
                ('features_title', models.CharField(default='Pourquoi choisir Numeria ?', max_length=200, verbose_name='Titre fonctionnalités')),
                ('features', models.JSONField(default=list, verbose_name='Fonctionnalités (JSON)')),
                ('testimonials', models.JSONField(default=list, verbose_name='Témoignages (JSON)')),
                ('meta_title', models.CharField(default='Accueil - Numeria Institute', max_length=60, verbose_name='Meta title')),
                ('meta_description', models.TextField(default='...', max_length=160, verbose_name='Meta description')),
            ],
            options={
                'verbose_name': "Page d'accueil",
                'verbose_name_plural': "Page d'accueil",
            },
        ),
    ]
