# Generated by Django 6.0.5 on 2026-05-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('unread', 'Non lu'), ('read', 'Lu'), ('replied', 'Répondu')], default='unread', max_length=20, verbose_name='Statut'),
        ),
    ]
