# Generated by Django 6.0.3 on 2026-04-07 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneRecrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la campagne')),
                ('filiere', models.CharField(max_length=100, verbose_name='Filière')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_limite', models.DateField(verbose_name='Date limite de candidature')),
                ('capacite_max', models.IntegerField(default=20, help_text='Laisser vide si illimité', verbose_name="Nombre maximum d'étudiants")),
                ('frais_candidature', models.DecimalField(decimal_places=0, default=0, help_text='0 = gratuit', max_digits=10, verbose_name='Frais de candidature (FCFA)')),
                ('est_active', models.BooleanField(default=True, verbose_name='Campagne active')),
                ('prerequis', models.TextField(blank=True, help_text='Diplômes requis, expérience, etc.', verbose_name='Prérequis')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campagne de recrutement',
                'verbose_name_plural': 'Campagnes de recrutement',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('brouillon', '📝 Brouillon'), ('soumise', '📤 Soumise'), ('en_revue', '🔍 En revue'), ('acceptee', '✅ Acceptée'), ('liste_attente', "⏳ Liste d'attente"), ('refusee', '❌ Refusée')], default='brouillon', max_length=20)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(default='Togolaise', max_length=100, verbose_name='Nationalité')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email_personnel', models.EmailField(max_length=254, verbose_name='Email personnel')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays de résidence')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('dernier_etablissement', models.CharField(max_length=200, verbose_name='Dernier établissement fréquenté')),
                ('niveau_etudes', models.CharField(max_length=100, verbose_name="Niveau d'études atteint")),
                ('diplome_obtenu', models.CharField(blank=True, max_length=200, verbose_name='Diplôme obtenu')),
                ('annee_obtention', models.IntegerField(blank=True, null=True, verbose_name="Année d'obtention")),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Moyenne générale (/20)')),
                ('cv', models.FileField(help_text='Format PDF, max 5MB', upload_to='candidatures/cv/', verbose_name='CV (PDF)')),
                ('lettre_motivation', models.FileField(help_text='Format PDF, max 5MB', upload_to='candidatures/lettres/', verbose_name='Lettre de motivation (PDF)')),
                ('releves_notes', models.FileField(help_text='Format PDF, max 5MB', upload_to='candidatures/releves/', verbose_name='Relevés de notes (PDF)')),
                ('autres_documents', models.FileField(blank=True, help_text='Certificats, attestations, etc. (PDF)', null=True, upload_to='candidatures/autres/', verbose_name='Autres documents (optionnel)')),
                ('motivation', models.TextField(verbose_name='Pourquoi souhaitez-vous intégrer cette formation ?')),
                ('experiences', models.TextField(blank=True, verbose_name='Expériences professionnelles ou associatives')),
                ('competences', models.TextField(blank=True, verbose_name='Compétences particulières')),
                ('source', models.CharField(blank=True, choices=[('google', 'Google / Recherche internet'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('bouche_oreille', 'Bouche à oreille'), ('presse', 'Presse / Média'), ('partenaire', 'Partenaire'), ('autre', 'Autre')], max_length=30, verbose_name='Comment avez-vous connu Numeria ?')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True, verbose_name='Commentaire interne')),
                ('paiement_effectue', models.BooleanField(default=False, verbose_name='Paiement effectué')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='admissions.campagnerecrutement')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidature', to='paiements.paiement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
