# Generated by Django 6.0.3 on 2026-04-14 01:39

import admissions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_fix_campaign_description_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='autres_documents',
            field=models.FileField(blank=True, help_text='Certificats, attestations, etc. (PDF, max 2MB)', null=True, upload_to='candidatures/autres/', validators=[django.core.validators.FileExtensionValidator(['pdf']), admissions.models.validate_file_size], verbose_name='Autres documents (optionnel)'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(help_text='Format PDF, max 2MB', upload_to='candidatures/cv/', validators=[django.core.validators.FileExtensionValidator(['pdf']), admissions.models.validate_file_size], verbose_name='CV (PDF)'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.FileField(help_text='Format PDF, max 2MB', upload_to='candidatures/lettres/', validators=[django.core.validators.FileExtensionValidator(['pdf']), admissions.models.validate_file_size], verbose_name='Lettre de motivation (PDF)'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='releves_notes',
            field=models.FileField(help_text='Format PDF, max 2MB', upload_to='candidatures/releves/', validators=[django.core.validators.FileExtensionValidator(['pdf']), admissions.models.validate_file_size], verbose_name='Relevés de notes (PDF)'),
        ),
    ]
