# Generated by Django 6.0.5 on 2026-05-30 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_candidature_autres_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Raison de refus'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traité le'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
    ]
