# Generated by Django 6.0.5 on 2026-05-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time_minutes',
            field=models.IntegerField(default=5, verbose_name='Temps de lecture (min)'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500, verbose_name='Tags'),
        ),
    ]
