# Generated by Django 6.0.3 on 2026-04-15 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug URL')),
                ('description_courte', models.CharField(help_text='Brève accroche (ex: "Bootcamp Python 8 semaines")', max_length=300, verbose_name='Description courte')),
                ('description_longue', models.TextField(verbose_name='Description complète')),
                ('type_formation', models.CharField(choices=[('bootcamp', 'Bootcamp (intense)'), ('workshop', 'Workshop (court)'), ('course', 'Cours (long)'), ('masterclass', 'Masterclass'), ('certification', 'Certification professionnelle')], max_length=20, verbose_name='Type')),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='debutant', max_length=20)),
                ('duree_heures', models.IntegerField(help_text='ex: 40 heures pour un bootcamp', verbose_name='Durée estimée (heures)')),
                ('image_couverture', models.ImageField(help_text='1200x630px recommandé', upload_to='formations/covers/', verbose_name='Image de couverture')),
                ('competences_visees', models.TextField(help_text='Une par ligne', verbose_name='Compétences visées')),
                ('prerequis', models.TextField(blank=True, help_text="Connaissances nécessaires avant de s'inscrire", verbose_name='Prérequis')),
                ('est_publiee', models.BooleanField(default=False, verbose_name='Publiée (visible publiquement)')),
                ('est_archivee', models.BooleanField(default=False, verbose_name="Archivée (plus d'inscriptions)")),
                ('nombre_etudiants_total', models.IntegerField(default=0, editable=False)),
                ('nombre_certifies', models.IntegerField(default=0, editable=False)),
                ('note_moyenne', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=3, verbose_name='Note moyenne')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('instructeurs', models.ManyToManyField(related_name='formations_enseignees', to=settings.AUTH_USER_MODEL, verbose_name='Instructeurs')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_paye_fcfa', models.IntegerField(verbose_name='Prix payé (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirmee', 'Confirmée (payée)'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('progression', models.IntegerField(default=0, verbose_name='Progression (%)')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation_paiement', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_formations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription formation',
                'verbose_name_plural': 'Inscriptions formations',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='CertificatFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_verification', models.CharField(help_text='Permet vérifier le certificat sans compte', max_length=64, unique=True, verbose_name='Token (URL vérification)')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Expiration (vide = pas d'expiration)")),
                ('note_finale', models.IntegerField(verbose_name='Note finale (%)')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='formation.inscriptionformation')),
            ],
            options={
                'verbose_name': 'Certificat formation',
                'verbose_name_plural': 'Certificats formations',
                'ordering': ['-date_obtention'],
            },
        ),
        migrations.CreateModel(
            name='LeconFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('contenu_html', models.TextField(verbose_name='Contenu (HTML)')),
                ('video_youtube', models.URLField(blank=True, verbose_name='Vidéo YouTube/Vimeo')),
                ('ressources_telechargeables', models.FileField(blank=True, upload_to='formations/resources/', verbose_name='Ressource téléchargeable (PDF, ZIP, etc)')),
                ('duree_minutes', models.IntegerField(default=30, verbose_name='Durée (minutes)')),
                ('exercice_code_html', models.TextField(blank=True, help_text='HTML personnalisé pour un exercice', verbose_name="HTML de l'exercice (si s/o)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='formation.formation')),
            ],
            options={
                'verbose_name': 'Leçon formation',
                'verbose_name_plural': 'Leçons formation',
                'ordering': ['formation', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_commencee', models.BooleanField(default=False)),
                ('est_terminees', models.BooleanField(default=False)),
                ('date_premiere_visite', models.DateTimeField(auto_now_add=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('temps_passe_minutes', models.IntegerField(default=0)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_lecons', to='formation.inscriptionformation')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.leconformation')),
            ],
            options={
                'verbose_name': 'Progression leçon',
                'verbose_name_plural': 'Progressions leçons',
            },
        ),
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='ex: "Cohort Jan 2026"', max_length=200, verbose_name='Nom de la session')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('date_debut', models.DateField(verbose_name='Date de début du cours')),
                ('date_fin', models.DateField(verbose_name='Date de fin du cours')),
                ('date_debut_inscriptions', models.DateField(verbose_name='Ouverture des inscriptions')),
                ('date_fin_inscriptions', models.DateField(verbose_name='Fermeture des inscriptions')),
                ('places_totales', models.IntegerField(default=30, verbose_name='Places disponibles')),
                ('prix_fcfa', models.IntegerField(help_text='ex: 150000 pour bootcamp 8 semaines', verbose_name='Prix (FCFA)')),
                ('prix_reduit_fcfa', models.IntegerField(blank=True, help_text='Si vide, pas de réduction', null=True, verbose_name='Prix réduit (FCFA)')),
                ('modalite', models.CharField(choices=[('presentiel', 'Présentiel'), ('visio', 'Visioconférence'), ('hybride', 'Hybride')], default='visio', max_length=20, verbose_name='Format')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée (pas encore inscriptions)'), ('ouverture', 'Ouverture (inscriptions en cours)'), ('fermee', "Fermée (plus d'inscriptions)"), ('en_cours', 'En cours de formation'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formation.formation', verbose_name='Formation')),
                ('instructeurs_session', models.ManyToManyField(blank=True, related_name='sessions_enseignees', to=settings.AUTH_USER_MODEL, verbose_name='Instructeurs (si différent de la formation)')),
            ],
            options={
                'verbose_name': 'Session de formation',
                'verbose_name_plural': 'Sessions de formation',
                'ordering': ['date_debut'],
            },
        ),
        migrations.AddField(
            model_name='inscriptionformation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formation.sessionformation'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['slug'], name='formation_f_slug_e2107f_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['est_publiee'], name='formation_f_est_pub_35197f_idx'),
        ),
        migrations.AddIndex(
            model_name='leconformation',
            index=models.Index(fields=['formation', 'ordre'], name='formation_l_formati_9d6ad7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progressionlecon',
            unique_together={('inscription', 'lecon')},
        ),
        migrations.AddIndex(
            model_name='sessionformation',
            index=models.Index(fields=['formation', 'statut'], name='formation_s_formati_904d21_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionformation',
            index=models.Index(fields=['date_fin_inscriptions'], name='formation_s_date_fi_9a7ed6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionformation',
            unique_together={('formation', 'slug')},
        ),
        migrations.AddIndex(
            model_name='inscriptionformation',
            index=models.Index(fields=['session', 'statut'], name='formation_i_session_10ed25_idx'),
        ),
        migrations.AddIndex(
            model_name='inscriptionformation',
            index=models.Index(fields=['etudiant'], name='formation_i_etudian_114599_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscriptionformation',
            unique_together={('session', 'etudiant')},
        ),
    ]
