# Generated by Django 6.0.3 on 2026-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='image_couverture',
            field=models.ImageField(blank=True, help_text='1200x630px recommandé', null=True, upload_to='formations/covers/', verbose_name='Image de couverture'),
        ),
    ]
