# Generated by Django 6.0.5 on 2026-05-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_alter_formation_image_couverture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='formation.formation')),
            ],
            options={
                'verbose_name': 'Module de formation',
                'verbose_name_plural': 'Modules de formation',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='FormationLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=300)),
                ('contenu', models.TextField(blank=True, help_text='Supporte HTML, LaTeX, Markdown.', verbose_name='Contenu')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL vidéo')),
                ('content_type', models.CharField(choices=[('text', 'Texte / Article'), ('video', 'Vidéo'), ('mixed', 'Mixte (Texte + Vidéo)'), ('exercise', 'Exercice pratique')], default='text', max_length=20, verbose_name='Type de contenu')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Aperçu gratuit')),
                ('duree_minutes', models.IntegerField(default=10, verbose_name='Durée (minutes)')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_lessons', to='formation.formation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='formation.formationmodule')),
            ],
            options={
                'verbose_name': 'Leçon de formation',
                'verbose_name_plural': 'Leçons de formation',
                'ordering': ['ordre'],
            },
        ),
    ]
