# Generated by Django 6.0.3 on 2026-04-07 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cours', models.CharField(choices=[('general', 'Cours général'), ('scolaire', 'Cours scolaire')], default='general', max_length=20, verbose_name='Type de cours')),
                ('cycle', models.CharField(blank=True, choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée')], max_length=20, null=True, verbose_name='Cycle scolaire')),
                ('classe', models.CharField(blank=True, choices=[('CP', 'CP  Cours Préparatoire'), ('CE1', 'CE1  Cours Élémentaire 1'), ('CE2', 'CE2  Cours Élémentaire 2'), ('CM1', 'CM1  Cours Moyen 1'), ('CM2', 'CM2  Cours Moyen 2'), ('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème'), ('2nde', 'Seconde'), ('1ere_A', 'Première A'), ('1ere_C', 'Première C'), ('1ere_D', 'Première D'), ('1ere_E', 'Première E'), ('1ere_F', 'Première F'), ('1ere_G', 'Première G'), ('Tle_A', 'Terminale A'), ('Tle_C', 'Terminale C'), ('Tle_D', 'Terminale D'), ('Tle_E', 'Terminale E'), ('Tle_F', 'Terminale F'), ('Tle_G', 'Terminale G')], max_length=20, null=True, verbose_name='Classe')),
                ('matiere', models.CharField(choices=[('python_scientifique', 'Python Scientifique'), ('fortran', 'Fortran & Calcul Haute Performance'), ('mathematica', 'Calcul Formel & Mathematica'), ('methodes_numeriques', 'Méthodes Numériques'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('nlp', 'NLP & IA pour Langues Africaines'), ('ia_deploiement', 'IA Appliquée & Déploiement'), ('maths', 'Mathématiques'), ('physique_chimie', 'Physique-Chimie'), ('svt', 'SVT — Sciences de la Vie et de la Terre'), ('francais', 'Français'), ('anglais', 'Anglais'), ('histoire_geo', 'Histoire-Géographie'), ('philosophie', 'Philosophie'), ('informatique', 'Informatique'), ('economie', 'Économie'), ('autre', 'Autre')], max_length=30, verbose_name='Matière')),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=20, verbose_name='Niveau')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('resume', models.CharField(max_length=300, verbose_name='Résumé court')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('nombre_lecons', models.IntegerField(default=0, verbose_name='Nombre de leçons')),
                ('video_youtube', models.URLField(blank=True, help_text="Collez l'URL YouTube ou Vimeo normale. Ex : https://youtu.be/ABC123", null=True, verbose_name='Vidéo YouTube / Vimeo principale')),
                ('est_gratuit', models.BooleanField(default=True, verbose_name='Gratuit')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('est_publie', models.BooleanField(default=False, verbose_name='Publié')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('progression', models.IntegerField(default=0)),
                ('est_termine', models.BooleanField(default=False)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='cours.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'cours')},
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('code_verification', models.CharField(max_length=32, unique=True, verbose_name='Code de vérification')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='cours.inscriptioncours')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(blank=True, help_text='Supporte le LaTeX ($...$) et le code (<pre><code>...)', verbose_name='Contenu')),
                ('ordre', models.IntegerField(default=1, verbose_name='Ordre')),
                ('duree_minutes', models.IntegerField(default=10, verbose_name='Durée (minutes)')),
                ('video_youtube', models.URLField(blank=True, help_text='URL YouTube ou Vimeo normale. Ex : https://youtu.be/ABC123', null=True, verbose_name='Vidéo YouTube / Vimeo')),
                ('est_publiee', models.BooleanField(default=True, verbose_name='Publiée')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='cours.cours')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['cours', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Supporte le LaTeX. Ex: Calculer $x^2 + 2x + 1$', verbose_name='Question')),
                ('choix_a', models.CharField(max_length=500, verbose_name='Choix A')),
                ('choix_b', models.CharField(max_length=500, verbose_name='Choix B')),
                ('choix_c', models.CharField(max_length=500, verbose_name='Choix C')),
                ('choix_d', models.CharField(max_length=500, verbose_name='Choix D')),
                ('bonne_reponse', models.CharField(choices=[('A', 'Choix A'), ('B', 'Choix B'), ('C', 'Choix C'), ('D', 'Choix D')], max_length=1, verbose_name='Bonne réponse')),
                ('corrige', models.TextField(help_text='Explication complète. Supporte le LaTeX et le code HTML.', verbose_name='Corrigé détaillé')),
                ('ordre', models.IntegerField(default=1, verbose_name='Ordre')),
                ('points', models.IntegerField(default=1, verbose_name='Points')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices', to='cours.lecon')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['lecon', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='TentativeExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_choisie', models.CharField(max_length=1)),
                ('est_correcte', models.BooleanField(default=False)),
                ('date_tentative', models.DateTimeField(auto_now_add=True)),
                ('numero_tentative', models.IntegerField(default=1)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='cours.exercice')),
            ],
            options={
                'verbose_name': 'Tentative',
                'verbose_name_plural': 'Tentatives',
                'ordering': ['-date_tentative'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completion', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_lecons', to=settings.AUTH_USER_MODEL)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='cours.lecon')),
            ],
            options={
                'verbose_name': 'Progression leçon',
                'verbose_name_plural': 'Progressions leçons',
                'unique_together': {('etudiant', 'lecon')},
            },
        ),
    ]
