# Generated by Django 6.0.3 on 2026-04-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('resume', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('matiere', models.CharField(choices=[('maths', 'Mathématiques'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('informatique', 'Informatique'), ('autre', 'Autre')], max_length=20)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], max_length=20)),
                ('nombre_lecons', models.IntegerField(default=0)),
                ('video_youtube', models.URLField(blank=True, null=True)),
                ('est_gratuit', models.BooleanField(default=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_publie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_creation'],
            },
        ),
    ]
