# Generated by Django 6.0.3 on 2026-04-14 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du tag')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#2DD4BF', max_length=7, verbose_name='Couleur (hex)')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='competences_visees',
            field=models.TextField(blank=True, help_text='Listez les compétences que les étudiants acquerront (séparées par des virgules)', verbose_name='Compétences visées'),
        ),
        migrations.AddField(
            model_name='cours',
            name='cours_prerequises',
            field=models.ManyToManyField(blank=True, related_name='cours_suivants', to='cours.Cours', verbose_name='Cours préalables'),
        ),
        migrations.AddField(
            model_name='cours',
            name='duree_estimee_heures',
            field=models.IntegerField(default=10, verbose_name='Durée estimée (heures)'),
        ),
        migrations.AddField(
            model_name='cours',
            name='langue',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('other', 'Autre')], default='fr', max_length=10, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='cours',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mots-clés SEO'),
        ),
        migrations.AddField(
            model_name='cours',
            name='nombre_etudiants_inscrits',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='cours',
            name='note_moyenne',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3, verbose_name='Note moyenne'),
        ),
        migrations.AddField(
            model_name='cours',
            name='ressources_externes',
            field=models.TextField(blank=True, help_text='Liens vers des ressources complémentaires (un par ligne)', verbose_name='Ressources externes'),
        ),
        migrations.AddField(
            model_name='cours',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL slug'),
        ),
        migrations.AddField(
            model_name='cours',
            name='taux_completion',
            field=models.IntegerField(default=0, editable=False, verbose_name='Taux de complétion (%)'),
        ),
        migrations.CreateModel(
            name='CertificatCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('gagne', 'Gagné'), ('expire', 'Expiré')], default='gagne', max_length=20, verbose_name='Statut')),
                ('numero_certificat', models.CharField(max_length=50, unique=True, verbose_name='Numéro de certificat')),
                ('score_final', models.IntegerField(default=100, verbose_name='Score final (%)')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='cours.Cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-date_obtention'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1/5 ⭐'), (2, '2/5 ⭐'), (3, '3/5 ⭐'), (4, '4/5 ⭐'), (5, '5/5 ⭐')], verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, max_length=500, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='cours.Cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_cours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='QuestionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('approuvee_par_admin', models.BooleanField(default=False)),
                ('votes_positifs', models.IntegerField(default=0)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_faq', to=settings.AUTH_USER_MODEL)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='cours.Cours')),
            ],
            options={
                'verbose_name': 'Question FAQ',
                'verbose_name_plural': 'Questions FAQ',
                'ordering': ['-votes_positifs', '-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cours', to='cours.tag', verbose_name='Tags'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['slug'], name='cours_cours_slug_ea015b_idx'),
        ),
        migrations.AddIndex(
            model_name='cours',
            index=models.Index(fields=['est_publie', '-date_creation'], name='cours_cours_est_pub_389982_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificatcours',
            unique_together={('etudiant', 'cours')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationcours',
            unique_together={('etudiant', 'cours')},
        ),
    ]
