# Generated by Django 6.0.5 on 2026-05-30 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_tag_cours_competences_visees_cours_cours_prerequises_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('instructions', models.TextField(help_text='Instructions en Markdown', verbose_name='Instructions')),
                ('starter_code', models.TextField(help_text="Code affiché à l'étudiant", verbose_name='Code de départ')),
                ('solution_code', models.TextField(help_text="Jamais montrée à l'étudiant", verbose_name='Solution')),
                ('expected_output', models.TextField(blank=True, help_text='Pour comparaison exacte ou contient', verbose_name='Output attendu')),
                ('test_code', models.TextField(blank=True, help_text='Assertions cachées (mode tests unitaires)', verbose_name='Code de tests')),
                ('evaluation_mode', models.CharField(choices=[('exact', 'Output exact'), ('contains', 'Output contient'), ('tests', 'Tests unitaires')], default='exact', max_length=20, verbose_name="Mode d'évaluation")),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10, verbose_name='Difficulté')),
                ('hint', models.TextField(blank=True, help_text='Affiché après 3 tentatives échouées', verbose_name='Indice')),
                ('max_attempts', models.IntegerField(default=0, help_text='0 = illimité', verbose_name='Tentatives max')),
                ('points', models.IntegerField(default=10, verbose_name='Points')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_exercises', to='cours.lecon', verbose_name='Leçon')),
            ],
            options={
                'verbose_name': 'Exercice de code',
                'verbose_name_plural': 'Exercices de code',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentCodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_submitted', models.TextField(verbose_name='Code soumis')),
                ('output_received', models.TextField(blank=True, verbose_name='Output reçu')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Tentative n°')),
                ('time_spent_seconds', models.IntegerField(default=0, verbose_name='Temps (s)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cours.codeexercise', verbose_name='Exercice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Soumission de code',
                'verbose_name_plural': 'Soumissions de code',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
