# Generated by Django 6.0.3 on 2026-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_lecon_progressionlecon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.CharField(blank=True, choices=[('CP', 'CP — Cours Préparatoire'), ('CE1', 'CE1 — Cours Élémentaire 1'), ('CE2', 'CE2 — Cours Élémentaire 2'), ('CM1', 'CM1 — Cours Moyen 1'), ('CM2', 'CM2 — Cours Moyen 2'), ('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème'), ('2nde', 'Seconde'), ('1ere_A', 'Première A'), ('1ere_C', 'Première C'), ('1ere_D', 'Première D'), ('1ere_E', 'Première E'), ('1ere_F', 'Première F'), ('1ere_G', 'Première G'), ('Tle_A', 'Terminale A'), ('Tle_C', 'Terminale C'), ('Tle_D', 'Terminale D'), ('Tle_E', 'Terminale E'), ('Tle_F', 'Terminale F'), ('Tle_G', 'Terminale G')], max_length=20, null=True, verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='cycle',
            field=models.CharField(blank=True, choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée')], max_length=20, null=True, verbose_name='Cycle scolaire'),
        ),
        migrations.AddField(
            model_name='cours',
            name='type_cours',
            field=models.CharField(choices=[('general', 'Cours général'), ('scolaire', 'Cours scolaire')], default='general', max_length=20, verbose_name='Type de cours'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='description',
            field=models.TextField(verbose_name='Description complète'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='est_gratuit',
            field=models.BooleanField(default=True, verbose_name='Gratuit'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='est_publie',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='matiere',
            field=models.CharField(choices=[('python_scientifique', 'Python Scientifique'), ('fortran', 'Fortran & Calcul Haute Performance'), ('mathematica', 'Calcul Formel & Mathematica'), ('methodes_numeriques', 'Méthodes Numériques'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('nlp', 'NLP & IA pour Langues Africaines'), ('ia_deploiement', 'IA Appliquée & Déploiement'), ('maths', 'Mathématiques'), ('physique_chimie', 'Physique-Chimie'), ('svt', 'SVT — Sciences de la Vie et de la Terre'), ('francais', 'Français'), ('anglais', 'Anglais'), ('histoire_geo', 'Histoire-Géographie'), ('philosophie', 'Philosophie'), ('informatique', 'Informatique'), ('economie', 'Économie'), ('autre', 'Autre')], max_length=30, verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='niveau',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='nombre_lecons',
            field=models.IntegerField(default=0, verbose_name='Nombre de leçons'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='resume',
            field=models.CharField(max_length=300, verbose_name='Résumé court'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='video_youtube',
            field=models.URLField(blank=True, help_text="Collez l'URL YouTube normale, elle sera convertie automatiquement", null=True, verbose_name='Vidéo YouTube principale'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='contenu',
            field=models.TextField(blank=True, help_text='Supporte le LaTeX ($...$) et le code (<pre><code>...)', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='duree_minutes',
            field=models.IntegerField(default=10, verbose_name='Durée (minutes)'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='est_publiee',
            field=models.BooleanField(default=True, verbose_name='Publiée'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='ordre',
            field=models.IntegerField(default=1, verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='video_youtube',
            field=models.URLField(blank=True, help_text='URL YouTube normale — convertie automatiquement', null=True, verbose_name='Vidéo YouTube'),
        ),
    ]
