# Generated by Django 6.0.5 on 2026-05-30 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_codeexercise_studentcodesubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='cours',
            name='meta_description',
            field=models.CharField(blank=True, help_text='160 caractères max', max_length=160, verbose_name='Meta description SEO'),
        ),
        migrations.AddField(
            model_name='cours',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Un prérequis par ligne', verbose_name='Prérequis'),
        ),
        migrations.AddField(
            model_name='cours',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publié le'),
        ),
        migrations.AddField(
            model_name='cours',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('revision', 'En révision'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut CMS'),
        ),
        migrations.AddField(
            model_name='cours',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Miniature'),
        ),
        migrations.AddField(
            model_name='lecon',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texte / Article'), ('video', 'Vidéo'), ('mixed', 'Mixte (Texte + Vidéo)'), ('exercise', 'Exercice pratique')], default='text', max_length=20, verbose_name='Type de contenu'),
        ),
        migrations.AddField(
            model_name='lecon',
            name='is_free_preview',
            field=models.BooleanField(default=False, help_text='Accessible sans inscription ni paiement', verbose_name='Aperçu gratuit'),
        ),
        migrations.AddField(
            model_name='lecon',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cours.Course')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='lecon',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecons_module', to='cours.module', verbose_name='Module'),
        ),
    ]
