# Generated by Django 6.0.5 on 2026-05-30 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_cours_created_by_cours_meta_description_and_more'),
        ('formation', '0003_formationmodule_formationlesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexercise',
            name='formation_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_exercises', to='formation.formationlesson', verbose_name='Leçon de formation'),
        ),
        migrations.AlterField(
            model_name='codeexercise',
            name='lecon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_exercises', to='cours.lecon', verbose_name='Leçon'),
        ),
        migrations.CreateModel(
            name='UserScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Sans titre', max_length=200, verbose_name='Titre')),
                ('code', models.TextField(default='', verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Script utilisateur',
                'verbose_name_plural': 'Scripts utilisateurs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
