# Generated by Django 6.0.5 on 2026-05-30 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_codeexercise_formation_lesson_and_more'),
        ('formation', '0003_formationmodule_formationlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Texte / Markdown / LaTeX'), ('video', 'Vidéo'), ('sandbox', 'Sandbox Python libre'), ('exercise', 'Exercice évalué')], max_length=20, verbose_name='Type')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('text_content', models.TextField(blank=True, verbose_name='Contenu Markdown / LaTeX')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL vidéo')),
                ('video_caption', models.CharField(blank=True, max_length=300, verbose_name='Légende')),
                ('sandbox_title', models.CharField(blank=True, default='Essaie toi-même', max_length=300)),
                ('sandbox_initial_code', models.TextField(blank=True, default='# Écris ton code ici\n')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_blocks', to='cours.codeexercise', verbose_name='Exercice')),
                ('formation_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='formation.formationlesson', verbose_name='Leçon de formation')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cours.lecon', verbose_name='Leçon de cours')),
            ],
            options={
                'verbose_name': 'Bloc de leçon',
                'verbose_name_plural': 'Blocs de leçon',
                'ordering': ['order'],
            },
        ),
    ]
