# Generated by Django 6.0.3 on 2026-04-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_alter_cours_video_youtube_alter_lecon_video_youtube_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='classe',
            field=models.CharField(blank=True, choices=[('CP', 'CP  Cours Préparatoire'), ('CE1', 'CE1  Cours Élémentaire 1'), ('CE2', 'CE2  Cours Élémentaire 2'), ('CM1', 'CM1  Cours Moyen 1'), ('CM2', 'CM2  Cours Moyen 2'), ('6eme', '6ème'), ('5eme', '5ème'), ('4eme', '4ème'), ('3eme', '3ème'), ('2nde', 'Seconde'), ('1ere_A', 'Première A'), ('1ere_C', 'Première C'), ('1ere_D', 'Première D'), ('1ere_E', 'Première E'), ('1ere_F', 'Première F'), ('1ere_G', 'Première G'), ('Tle_A', 'Terminale A'), ('Tle_C', 'Terminale C'), ('Tle_D', 'Terminale D'), ('Tle_E', 'Terminale E'), ('Tle_F', 'Terminale F'), ('Tle_G', 'Terminale G')], max_length=20, null=True, verbose_name='Classe'),
        ),
    ]
