# Generated by Django 6.0.5 on 2026-05-31 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_lessonblock'),
        ('formation', '0003_formationmodule_formationlesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Texte / Markdown / LaTeX'), ('video', 'Vidéo'), ('sandbox', 'Sandbox Python libre'), ('exercise', 'Exercice de code évalué'), ('mcq', 'Question à choix multiples')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_blocks', to='cours.codeexercise', verbose_name='Exercice de code'),
        ),
        migrations.CreateModel(
            name='MCQExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('question', models.TextField(verbose_name='Question')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication')),
                ('hint', models.TextField(blank=True, verbose_name='Indice')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10)),
                ('points', models.IntegerField(default=5, verbose_name='Points')),
                ('max_attempts', models.IntegerField(default=0, verbose_name='Tentatives max (0=illimité)')),
                ('allow_multiple_correct', models.BooleanField(default=False, verbose_name='Plusieurs bonnes réponses possibles')),
                ('shuffle_choices', models.BooleanField(default=True, verbose_name='Mélanger les choix')),
                ('show_explanation_on_wrong', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mcq_exercises', to=settings.AUTH_USER_MODEL)),
                ('formation_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_exercises', to='formation.formationlesson', verbose_name='Leçon de formation')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_exercises', to='cours.lecon', verbose_name='Leçon de cours')),
            ],
            options={
                'verbose_name': 'Exercice QCM',
                'verbose_name_plural': 'Exercices QCM',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MCQChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texte du choix')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Bonne réponse')),
                ('order', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True, verbose_name='Feedback spécifique')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='cours.mcqexercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='mcq_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_blocks', to='cours.mcqexercise', verbose_name='QCM'),
        ),
        migrations.CreateModel(
            name='MCQSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt_number', models.IntegerField(default=1)),
                ('points_earned', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cours.mcqexercise')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='submissions', to='cours.mcqchoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MCQGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cours.mcqexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exercise')},
            },
        ),
    ]
