# Generated by Django 6.0.3 on 2026-04-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_exercice_tentativeexercice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('code_verification', models.CharField(max_length=32, unique=True, verbose_name='Code de vérification')),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='cours.inscriptioncours')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ['-date_emission'],
            },
        ),
    ]
