# Generated by Django 6.0.5 on 2026-05-31 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_alter_lessonblock_block_type_and_more'),
        ('formation', '0003_formationmodule_formationlesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codeexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Créé le'),
        ),
        migrations.AddField(
            model_name='codeexercise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_code_exercises', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='lessonblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Texte / Markdown / LaTeX'), ('video', 'Vidéo'), ('sandbox', 'Sandbox Python libre'), ('exercise', 'Exercice de code Python'), ('mcq', 'Question à choix multiples'), ('fill_blank', 'Texte à trous'), ('true_false', 'Vrai ou Faux'), ('code_order', 'Ordonner le code'), ('matching', 'Associations'), ('short_answer', 'Réponse courte')], max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='CodeOrderExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('instructions', models.TextField(blank=True)),
                ('correct_order', models.JSONField(default=list)),
                ('distractor_lines', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10)),
                ('points', models.IntegerField(default=10)),
                ('hint', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('max_attempts', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('formation_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_order_exercises', to='formation.formationlesson')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_order_exercises', to='cours.lecon')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='code_order_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_blocks', to='cours.codeorderexercise'),
        ),
        migrations.CreateModel(
            name='FillBlankExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('instructions', models.TextField(blank=True)),
                ('text_with_blanks', models.TextField(help_text='Use {{blank_1}}, {{blank_2}}, … markers')),
                ('answers', models.JSONField(default=dict)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10)),
                ('points', models.IntegerField(default=5)),
                ('hint', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('max_attempts', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('formation_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank_exercises', to='formation.formationlesson')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank_exercises', to='cours.lecon')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='fill_blank_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_blocks', to='cours.fillblankexercise'),
        ),
        migrations.CreateModel(
            name='MatchingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('instructions', models.TextField(blank=True)),
                ('pairs', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10)),
                ('points', models.IntegerField(default=8)),
                ('hint', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('formation_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_exercises', to='formation.formationlesson')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_exercises', to='cours.lecon')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='matching_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_blocks', to='cours.matchingexercise'),
        ),
        migrations.CreateModel(
            name='ShortAnswerExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('question', models.TextField()),
                ('accepted_answers', models.JSONField(default=list)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('strip_whitespace', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10)),
                ('points', models.IntegerField(default=5)),
                ('hint', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('max_attempts', models.IntegerField(default=3)),
                ('is_code_answer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('formation_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_answer_exercises', to='formation.formationlesson')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_answer_exercises', to='cours.lecon')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='short_answer_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_blocks', to='cours.shortanswerexercise'),
        ),
        migrations.CreateModel(
            name='TrueFalseExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('statements', models.JSONField(default=list)),
                ('points_per_statement', models.IntegerField(default=2)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10)),
                ('hint', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('formation_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='true_false_exercises', to='formation.formationlesson')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='true_false_exercises', to='cours.lecon')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lessonblock',
            name='true_false_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_blocks', to='cours.truefalseexercise'),
        ),
        migrations.CreateModel(
            name='CodeOrderGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cours.codeorderexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_order_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cours.codeexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note exercice code',
                'unique_together': {('student', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='FillBlankGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cours.fillblankexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_blank_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='MatchingGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cours.matchingexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='ShortAnswerGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cours.shortanswerexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='TrueFalseGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='cours.truefalseexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_false_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'exercise')},
            },
        ),
    ]
