# Generated by Django 6.0.3 on 2026-04-06 02:04

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo')),
                ('bio', models.TextField(blank=True, help_text='Parlez-nous de vous en quelques mots', max_length=500, null=True)),
                ('pays', models.CharField(blank=True, default='Togo', max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_etudes', models.CharField(blank=True, choices=[('lycee', 'Lycée'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('professionnel', 'Professionnel'), ('autre', 'Autre')], max_length=20, null=True)),
                ('domaine', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
