# Generated by Django 6.0.3 on 2026-04-02 02:00

import comptes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=comptes.models.chemin_photo_profil, verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='domaine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
