# Generated by Django 6.0.3 on 2026-04-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='est_menteur',
            field=models.BooleanField(default=False, help_text='Peut répondre aux questions des étudiants', verbose_name='Accès mentor activé'),
        ),
        migrations.AddField(
            model_name='profil',
            name='est_verifiee',
            field=models.BooleanField(default=False, verbose_name='Compte vérifié'),
        ),
        migrations.AddField(
            model_name='profil',
            name='langue_preference',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue préférée'),
        ),
        migrations.AddField(
            model_name='profil',
            name='nombre_abonnements',
            field=models.IntegerField(default=0, verbose_name="Nombre d'abonnements"),
        ),
        migrations.AddField(
            model_name='profil',
            name='nombre_abonnes',
            field=models.IntegerField(default=0, verbose_name="Nombre d'abonnés"),
        ),
        migrations.AddField(
            model_name='profil',
            name='nombre_messages_prives',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profil',
            name='notifications_activees',
            field=models.BooleanField(default=True, verbose_name='Notifications activées'),
        ),
        migrations.AddField(
            model_name='profil',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Auto')], default='auto', max_length=10, verbose_name='Préférence thème'),
        ),
    ]
