# Generated by Django 6.0.3 on 2026-05-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_profil_est_menteur_profil_est_verifiee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor')], default='mentee', help_text='Rôle de l’utilisateur dans la plateforme.', max_length=20, verbose_name='Rôle utilisateur'),
        ),
    ]
